apiVersion: apps/v1
kind: Deployment
metadata:
  name: bubblesort-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bubblesort
  template:
    metadata:
      labels:
        app: bubblesort
    spec:
      containers:
      - name: bubblesort
        image: bubblesort:latest
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "while true; do /app/bubblesort; sleep 10; done"]
        ports:
          - containerPort: 8080