name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ dpkg-dev

    - name: Build
      run: make

    - name: Fix permissions
      run: |
        chmod +x build/main
        chmod +x cicd/test.sh
        
    - name: Test
      run: ./cicd/test.sh

    - name: Build DEB
      run: make deb

    - name: Upload DEB
      uses: actions/upload-artifact@v4
      with:
        name: bubblesort
        path: deb_package.deb